#!/bin/sh

ENABLED=yes
PROCS=igmpproxy
ARGS="/opt/etc/igmpproxy.conf"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
